f = open('/Users/denny/stock_screener/momentum_scanner.py', 'w')
tickers = ['AAPL','MSFT','NVDA','GOOGL','AMZN','META','TSLA','AVGO','AMD','ORCL','PLTR','CRM','SNOW','DDOG','NET','ARM','SMCI','SOFI','MSTR','COIN','NFLX','DIS','ROKU','SPOT','UBER','ABNB','SQ','PYPL','HOOD','NU','V','MA','JPM','BAC','WFC','GS','MS','XOM','CVX','COP','OXY','JNJ','PFE','MRNA','LLY','ABBV','BMY','MRK','AMGN','COST','WMT','TGT','HD','LOW','BA','LMT','RTX','NOC','NIO','RIVN','LCID','XPEV','F','GM','INTC','QCOM','MU','AMAT','KLAC','TXN','ADI','MRVL','ENPH','FSLR','ALAB','AEHR','IOT','COHR','SITM','MARA','RIOT','CRWD','PANW','ZM','SHOP','BABA','JD','PDD','RKLB','ASTS','GME','AMC']
f.write('import yfinance as yf\n')
f.write('import pandas as pd\n')
f.write('import streamlit as st\n')
f.write('import os, json\n')
f.write('from datetime import datetime\n')
f.write(f'ALL_TICKERS = {tickers}\n')
f.write('WATCHLIST_FILE = os.path.expanduser("~/stock_screener/watchlist.json")\n')
f.write('def load_watchlist():\n')
f.write('    if os.path.exists(WATCHLIST_FILE):\n')
f.write('        with open(WATCHLIST_FILE) as wf: return json.load(wf)\n')
f.write('    return []\n')
f.write('def save_watchlist(wl):\n')
f.write('    with open(WATCHLIST_FILE, "w") as wf: json.dump(wl, wf)\n')
f.write('def get_stock_data(ticker):\n')
f.write('    try:\n')
f.write('        stock = yf.Ticker(ticker)\n')
f.write('        info = stock.info\n')
f.write('        hist = stock.history(period="5d").dropna(subset=["Close"])\n')
f.write('        if len(hist) >= 2:\n')
f.write('            prev = float(hist["Close"].iloc[-2])\n')
f.write('            curr = float(hist["Close"].iloc[-1])\n')
f.write('            chg = round(((curr-prev)/prev)*100,2)\n')
f.write('            vol = int(hist["Volume"].iloc[-1])\n')
f.write('            avg_vol = int(hist["Volume"].mean())\n')
f.write('            vol_spike = round(vol/avg_vol,2) if avg_vol>0 else 0\n')
f.write('            rec = info.get("recommendationKey","none")\n')
f.write('            rating = "⭐ STRONG BUY" if rec=="strong_buy" else "✅ BUY" if rec=="buy" else "⏸ HOLD" if rec=="hold" else "❌ SELL" if rec=="sell" else "➖ N/A"\n')
f.write('            return {"ticker":ticker,"price":curr,"chg":chg,"rating":rating,"target":info.get("targetMeanPrice","N/A"),"vol_spike":vol_spike,"high":info.get("fiftyTwoWeekHigh",0),"low":info.get("fiftyTwoWeekLow",0),"sector":info.get("sector","N/A")}\n')
f.write('    except: pass\n')
f.write('    return None\n')
f.write('st.set_page_config(page_title="Stock Scanner Pro", page_icon="📈", layout="wide")\n')
f.write('watchlist = load_watchlist()\n')
f.write('tab1, tab2 = st.tabs(["📈 Scanner", "⭐ Watchlist"])\n')
f.write('with tab1:\n')
f.write('    st.title("📈 Stock Scanner Pro")\n')
f.write('    st.caption(f"Scanning {len(ALL_TICKERS)} stocks")\n')
f.write('    with st.sidebar:\n')
f.write('        st.subheader("⚙️ Filters")\n')
f.write('        change_range = st.slider("% Change Range", -20, 100, (0, 100))\n')
f.write('        min_change, max_change = change_range\n')
f.write('        min_price = st.number_input("Min Price $", value=1)\n')
f.write('        max_price = st.number_input("Max Price $", value=1000)\n')
f.write('        min_vol = st.slider("Min Vol Spike", 0.0, 10.0, 0.0, step=0.5)\n')
f.write('        extra = st.text_input("Look up any ticker", "").upper().strip()\n')
f.write('        run = st.button("🚀 Run Scan", use_container_width=True)\n')
f.write('    if run:\n')
f.write('        if extra:\n')
f.write('            d = get_stock_data(extra)\n')
f.write('            if d:\n')
f.write('                st.success(f"Found {extra}!")\n')
f.write('                c1,c2,c3,c4 = st.columns(4)\n')
f.write('                c1.metric("Price", f"${round(d[\'price\'],2)}")\n')
f.write('                c2.metric("Change", f"{d[\'chg\']}%")\n')
f.write('                c3.metric("Rating", d["rating"])\n')
f.write('                c4.metric("Vol Spike", f"{d[\'vol_spike\']}x")\n')
f.write('                if st.button("+ Watchlist"):\n')
f.write('                    if extra not in watchlist:\n')
f.write('                        watchlist.append(extra)\n')
f.write('                        save_watchlist(watchlist)\n')
f.write('            else:\n')
f.write('                st.error(f"Could not find {extra}")\n')
f.write('        else:\n')
f.write('            results = []\n')
f.write('            bar = st.progress(0)\n')
f.write('            for i,ticker in enumerate(ALL_TICKERS):\n')
f.write('                bar.progress((i+1)/len(ALL_TICKERS), text=f"Scanning {ticker}...")\n')
f.write('                d = get_stock_data(ticker)\n')
f.write('                if d:\n')
f.write('                    if float(min_price)<=d["price"]<=float(max_price) and float(min_change)<=d["chg"]<=float(max_change) and (d["vol_spike"]>=float(min_vol) if min_vol>0 else True):\n')
f.write('                        results.append(d)\n')
f.write('            bar.empty()\n')
f.write('            if results:\n')
f.write('                results = sorted(results, key=lambda x: x["chg"], reverse=True)\n')
f.write('                c1,c2,c3 = st.columns(3)\n')
f.write('                c1.metric("Scanned", len(ALL_TICKERS))\n')
f.write('                c2.metric("Passed", len(results))\n')
f.write('                c3.metric("Strong Buys", sum(1 for r in results if "STRONG BUY" in r["rating"]))\n')
f.write('                st.divider()\n')
f.write('                for r in results:\n')
f.write('                    with st.expander(f"{r[\'ticker\']} — ${round(r[\'price\'],2)} — {r[\'chg\']}% — {r[\'rating\']}"):\n')
f.write('                        c1,c2,c3,c4 = st.columns(4)\n')
f.write('                        c1.metric("Price", f"${round(r[\'price\'],2)}")\n')
f.write('                        c2.metric("Change", f"{r[\'chg\']}%")\n')
f.write('                        c3.metric("Target", f"${r[\'target\']}")\n')
f.write('                        c4.metric("Vol
